- id: check-complex-migrations
  name: check-complex-migrations-hook
  entry: check_complex_migrations
  description: pre-commit hooks for merging content from different files to one
  language: python
